version: '3.8'

services:
  database:
    image: postgres:17-alpine
    container_name: sqlx_demo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sqlx_demo_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: