//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
// Note that the device type is an enum under schema 'kres'.
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "kres.device_type")]
pub enum DeviceType {
    #[sea_orm(string_value = "ngc20")]
    Ngc20,
    #[sea_orm(string_value = "elexant5010i")]
    Elexant5010i,
    #[sea_orm(string_value = "elexant40x0i")]
    Elexant40x0i,
}
